# Generated by Django 4.1 on 2022-09-20 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=20000)),
                ('d_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 20, 19, 37, 54, 960294))),
            ],
        ),
    ]
